
version: '3'

services:

  # 
  # Our client container.  We'll SSH form here.
  # 
  client:
    build:
      context: .
      dockerfile: files/Dockerfile-client
    volumes:
      - ./files/entrypoint-client.sh:/entrypoint.sh
      - ./files/motd-client:/etc/motd
      - ./files/ssh-config-client:/root/.ssh/config
      - ./keys:/keys
      - .:/mnt

  server:
    #
    # Our server container.  This will accept SSH keys.
    # 
    # Docs for this excelent container available at:
    # 
    # https://github.com/panubo/docker-sshd
    # 
    build:
      context: .
      dockerfile: files/Dockerfile-server

    volumes:
      - ./files/entrypoint-server.sh:/entrypoint.sh
      - ./files/sshd-config-server:/etc/ssh/sshd_config
      - ./keys/my-key.pub:/root/.ssh/authorized_keys
      - ./files/motd-server:/etc/motd
      - ./files/profile-server:/profile
      - .:/mnt

    environment:
      - SSH_ENABLE_ROOT=true


  ca:
    #
    # Our ca container.  This will only accept SSH keys signed with the CA.
    # 
    # Docs for this excelent container available at:
    # 
    # https://github.com/panubo/docker-sshd
    # 
    build:
      context: .
      dockerfile: files/Dockerfile-ca

    volumes:
      - ./files/entrypoint-ca.sh:/entrypoint.sh
      - ./files/sshd-config-ca:/etc/ssh/sshd_config
      - ./keys/ca.pub:/ca.pub
      - ./files/motd-ca:/etc/motd
      - ./files/profile-ca:/profile
      - .:/mnt

    environment:
      - SSH_ENABLE_ROOT=true


